volumes:
  postgres:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${NODE_ENV:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    environment:
      RAILS_ENV: ${RAILS_ENV:-production}
      NODE_ENV: ${NODE_ENV:-production}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
